apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cluster-autoscaler
    repo: https://kubernetes.github.io/autoscaler
    version: 9.29.1
    releaseName: cluster-autoscaler
    namespace: kube-system
    valuesFile: values.yaml
