apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.monitoring.svc.cluster.local:9090']

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana.monitoring.svc.cluster.local:3000']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']

      - job_name: 'external-alb'
        metrics_path: /metrics
        static_configs:
          - targets: ['prometheus.cgclab.shop']
      
      - job_name: 'argocd'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: argocd-server
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: argocd

