apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cgc
  labels:
    app: app-cgc
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: app-cgc
  template:
    metadata:
      labels:
        app: app-cgc
    spec:
      revisionHistoryLimit: 3
      containers:
        - name: app
          image: 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/wocgc:dae0ff0-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/data-access.properties
              subPath: data-access.properties
            - name: secret-volume
              mountPath: /app/config/secret.properties
              subPath: secret.properties
      volumes:
        - name: config-volume
          configMap:
            name: db-config
            items:
              - key: data-access.properties
                path: data-access.properties
        - name: secret-volume
          secret:
            secretName: db-secret
            items:
              - key: secret.properties
                path: secret.properties

