apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: elasticsearch
    repo: https://helm.elastic.co
    releaseName: elasticsearch
    version: 8.5.1
    namespace: logging
    valuesFile: values.yaml
