apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    # 로그 수집 (CRI 포맷)
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      format cri
      read_from_head true
    </source>

    # Kubernetes 메타데이터 추가
    <filter **>
      @type kubernetes_metadata
    </filter>

    # elasticsearch 로그 제외
    <filter kubernetes.**>
      @type grep
      <exclude>
        key $.kubernetes.pod_name
        pattern ^elasticsearch-master.*
      </exclude>
    </filter>

    # kube-system 네임스페이스 제외
    <filter kubernetes.**>
      @type grep
      <exclude>
        key $.kubernetes.namespace_name
        pattern ^kube-system$
      </exclude>
    </filter>

    # 의미 있는 에러 메시지만 수집
    <filter **>
      @type grep
      <regexp>
        key message
        pattern (ERROR|Error|WARN|Warning|FATAL|Exception|Fail|fail)
      </regexp>
    </filter>

    # 레코드에 추가 정보 삽입
    <filter **>
      @type record_transformer
      enable_ruby true
      <record>
        hostname ${hostname}
        container_name ${record["kubernetes"]["container_name"]}
        namespace ${record["kubernetes"]["namespace_name"]}
        pod ${record["kubernetes"]["pod_name"]}
      </record>
    </filter>

    # Elasticsearch로 전송
    <match **>
      @type elasticsearch
      host elasticsearch-master.logging.svc.cluster.local
      port 9200
      scheme https
      ssl_verify true
      ca_file /fluentd/etc/ca.crt
      logstash_format true
      logstash_prefix fluentd-error  # error 인덱스 구분
      logstash_dateformat %Y.%m.%d
      user elastic
      password XYMhzdMYCAdgJXka
      reconnect_on_error true
      reload_connections true
      include_tag_key true
      type_name _doc
      time_key @timestamp                  # Kibana에서 timestamp로 인식 가능
      time_key_format %Y-%m-%dT%H:%M:%S%z  # ISO8601 형식
    </match>

