# fluentd-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: logging
roleRef:
  kind: ClusterRole
  name: fluentd-clusterrole
  apiGroup: rbac.authorization.k8s.io

