apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Wocgc/petclinic-eks.git
    targetRevision: main
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
